### ISSUE TITLE
absolutely no wand works

### ISSUE THREAD

**Issue by CandyPillager** [Flemmli97/MobBattle#10]
#### Steps to reproduce:

I'm trying to do a mob battle of Ender Dragon vs Mighty Ender Chicken, but they wont get affected by the wands

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- MobBattle: 2.3.3

#### Other Mods (If you think it might be cause of an incompability):

Draconic evolution, optifine, mighty ender chicken

**Comment by Flemmli97** [comment]
the enderdragon is special. it wont work on it
