### ISSUE TITLE
Mob Battle Mod Unable to Share

### ISSUE THREAD

**Issue by CraftyCube** [Flemmli97/MobBattle#16]
### Modloader

Forge

### Minecraft version

1.16.5

### Modloader version

latest

### Mod version

latest 1.16.5

### Description

I am unable to "share" your project using url, making it so I am unable to install on my server. I have installed this same version on my server in the past but I now cannot. I am using aternos (which requires url sharing to be able to install mods). I really enjoy your mod and would prefer if you fixed this.

### Steps to reproduce

1. Step one

### Logs

https://gist.github.com/

**Comment by Flemmli97** [comment]
turned on. for now
