### ISSUE TITLE
[Feature Request]: Team Battle AI changes

### ISSUE THREAD

**Issue by Yellowbross** [Flemmli97/MobBattle#18]
### Suggestions

1: invulnerability
-mobs on teams shouldn't try to target mobs with the Invulnerable NBT; self explanatory

2: "don't affect" config list option
-a blacklist for mobs that the team battle AI can't affect would be nice, mainly for mods that summon healer minions, such as barako and the barakoaya from Mowzie's Mobs since they use attack targets to decide who to heal, breaking their AI when on teams with this mod

3: "attack mode" config option
-mobs on teams seem to focus on only one target and ignore all other targets, which can be bad in certain cases such as raid battles, where raiders will combo the mob like crazy while the mob is stuck trying to target a raider 40 blocks away. 
-when set to 1, team battle AI will work like it does right now
-when set to 2, mobs on teams will change their target automatically if hit by a mob on another team

4: mobs without a team
-i've noticed on 1.19 mobs on teams will target mobs without teams; i think there should be a "true-false" config option for if mobs on teams should automatically try to target mobs without teams, it can cause problems with raid battles as mobs on the defending team will target the villagers even if they're invulnerable

### Solution

1: in whatever system the mod uses to detect nearby enemies, make sure the mob isn't invulnerable before setting the target

2: if a mob's registry name does not match an entry in the config list, proceed with giving the mob team battle AI

3: in option 2, either give the mob a "revenge" target goal or use events to set its target automatically when hurt by an enemy

4: if the config option is set to "false", check if the mob has its own team before setting target

i'd like to stress these suggestions as important to add, especially 3

**Comment by Flemmli97** [comment]
see the changelog for v 2.4.3
