### ISSUE TITLE
1.8.9 Mob Fighter doesn't work

### ISSUE THREAD

**Issue by NefariousIntent2** [Flemmli97/MobBattle#21]
### Modloader

Forge

### Minecraft version

1.8.9

### Modloader version

11.15.1.2318

### Mod version

2.0.0 [Final]

### Description

Using the mob enrager I can't engage any mobs, I have disabled all mods and they dont work. Also the textures are bugged.

### Steps to reproduce

1. Step one
Use 1.8.9 and the forge version and the mod version above.
2. Step two
Then the textures will be bugged and the enrage stick won't work.

### Mods that might affect the issue

It can't be a incompability because I have 7 mods. I have disabled all of them and the issue persists.

### Logs

It didn't crash

**Comment by Flemmli97** [comment]
1.8.9 is dead. it will not get more updates

**Comment by NefariousIntent2** [comment]
> 1.8.9 is dead. it will not get more updates

If its broken you might as well remove the downloads to it, useless junk mod.
