### ISSUE TITLE
Team command block not affecting mobs on fabric

### ISSUE THREAD

**Issue by KaratFeng** [Flemmli97/MobBattle#25]
### Modloader

Fabric

### Minecraft version

1.19.2

### Modloader version

fabric - 0.14.21

### Mod version

mobbattle-1.19.4-2.4.3.1-fabric.jar

### Description

Using the team sticks work but using commands to place mobs in team are not making them attack each other

### Steps to reproduce

1. Create 2 teams with different name
2. place 2 command blocks set them to repeating always active
3. rename one for example /team join Mob1 @e[type=minecraft:spider]
4. rename the other for example /team join Mob2 @e[type=minecraft:pillager]
5. summon both mobs and watch them not fight

### Mods that might affect the issue

I tested with only the Mob battle mod

### Logs

[latest.log](https://github.com/Flemmli97/MobBattle/files/11973499/latest.log)

**Comment by KaratFeng** [comment]
did more testing, its an incompatibiility with replay mod

**Comment by KaratFeng** [comment]
With more testing, quiting and reloading the world make the already assigned mobs to attack the other team, but not new mobs

**Comment by Flemmli97** [comment]
this is because the things only get handled during mob spawn and not anytime else.
cant really be fixed as when adding an entity to a team a lot of context is not provided.
you can spawn entities with a team by providing a `Team` tag in the entity tag
