### ISSUE TITLE
crash on teams fighting

### ISSUE THREAD

**Issue by AndrewG587** [Flemmli97/MobBattle#26]
### Modloader

Fabric

### Minecraft version

1.20.1

### Modloader version

Fabric Loader version: 0.14.21 FabricAPI version: 0.85.0

### Mod version

2.4.4

### Description

Minecraft(singleplayer)/Server(multiplayer) crashes when a team eliminates all mobs of another team in the area. crash report says "Description: Ticking entity

java.lang.NullPointerException: Cannot invoke 'net.minecraft.class_1309.method_5864()' because 'livingEntity' is null
	at io.github.flemmli97.mobbattle.handler.EntityAIHurt.method_6266(EntityAIHurt.java:37)"

### Steps to reproduce

1. Add mobs to one team and add more to another.
2. Once one team eliminates all mobs in sight on the other, the game crashes almost same tick

### Mods that might affect the issue

idk

### Logs

https://paste.gg/p/anonymous/f9a89fc4ede74d71a30497cf199354ec

**Comment by AndrewG587** [comment]
only happens with teams

**Comment by miz-fan** [comment]
Modloader
Forge

Minecraft version
1.18.2

Modloader version
Forge - 40.2.0

Mod version
2.4.6

Description

Download the latest version 2.4.6, there will still be the same problem, this problem has not been fixed
