### ISSUE TITLE
My first Issue to fix it

### ISSUE THREAD

**Issue by giovy14** [Flemmli97/MobBattle#28]
### Modloader

Forge

### Minecraft version

1.20.1

### Modloader version

Forge (47.1.43)

### Mod version

mobbattle-1.20.1-2.4.6-forge

### Description

So, while I was loading the Minecraft world, it happened that when you did the loading, that is, 100%, Okay? The game crashed.

### Steps to reproduce

So, while I was loading the Minecraft world, it happened that when you did the loading, that is, 100%, Okay? The game crashed.

### Mods that might affect the issue

No, nothing.

### Logs

So, while I was loading the Minecraft world, it happened that when you did the loading, that is, 100%, Okay? The game crashed.

**Comment by Flemmli97** [comment]
no logs so cant help. provide the logs if you want help. it even says so in the template
