### ISSUE TITLE
Your request: crashlogs 

### ISSUE THREAD

**Issue by ReporterToTheMax** [Flemmli97/MobBattle#3]
Although you can easily reproduce this in its 'compiled' version, I don't know if you can still do the same when it comes to your workspace so here's the crash report:

Link 1: https://pastebin.com/YdCffrGK - Caused by a player in blue team get attacked by a zombie with no team
Link 2:https://pastebin.com/i63TbD0r - Right click the item in mid air

**Comment by Flemmli97** [comment]
thx, found it, fixed in the next release
