### ISSUE TITLE
New Versions

### ISSUE THREAD

**Issue by giovy14** [Flemmli97/MobBattle#35]
### Suggestions

There are many very important things we want to have, namely, versions: 1.20.4, 1.20.3, 1.20.2, so add these versions by updating the mod, kindly.       BY GIOVANNI SANTORO

### Solution

And also, It would be cool if you added, Skeletons with crossbows and zombies with bows and crossbows, you know, like: Wither Skeleton with bow, I mean, It'll be cool.

**Comment by Flemmli97** [comment]
the mod will for now stay on 1.20.1.
and you can just... give the skeletons stuff with the armor editor
