### ISSUE TITLE
[Feature Request]: kill counter for teams

### ISSUE THREAD

**Issue by PiggySkillsX** [Flemmli97/MobBattle#38]
### Suggestions

It would be great to have a way to track how many mobs have been killed by a mob team. A collective kill counter that can be easily displayed and reset. Might be useful when you have massive (or endless) battles and you want to see some objective indicators of how certain teams are performing.

### Solution

When a mob that has a team directly kills something else, 1 point is being added to team kill count. Each individual mob that has a team contributes to collective kill count of the team. 
To manage kill counts, a new wand can be added. If you give this wand a name that is matching existing team name, you can see team kills (right click) and reset them (shift+right click). Adding a new "/killcount" command is also an option.
If this feature somehow turns out to be performance hungry, there should be a config option to turn this off.

If what I'm proposing is too difficult to make, there's another option. Instead of kill counter, there can be death counter. Works almost the same way, but every time an entity that has a team dies, 1 point is being added to a collective death count.

**Comment by Flemmli97** [comment]
if a killcounter is implemented when if a mob dies by non mob cause (e.g. lava) then it will obviously not be tracked if that is fine

**Comment by PiggySkillsX** [comment]
Most mobs don't have the ability to make an "indirect" kill anyway, so it's fine.
