### ISSUE TITLE
Accidental Spawn Egg Changes

### ISSUE THREAD

**Issue by TwoBoogerFace** [Flemmli97/MobBattle#4]
The Extended Spawn Egg has strange controls that cause issues while using it for what the mod is intended for. When an NBT is saved and the mob is spawned in bulk it resaves the mob without the NBT because when the mob is clicked again, it overwrites the previous NBT with the default. 
For example, I want to have a battle between a Naga and 12 Twilight Lich from the Twilight Forest mod. I take down the sheilds of the Lich because mobs can't do that. I save the NBT, spawn it without the shields and I click the the Lich I just spawned and I spawn a shielded Lich.
When first looked at, it seems that making saving the NBT just clicking, and the default mob sneak-click. This is not a good solution, because let's say I want a battle like explained above, but instead of a Naga, it's 5 Zombie Pigman in full diamond. If I spawn the Lich first, and then spawn the Pigman, and a Lich happens to walk past, that Pigman egg would be changed into another Lich egg and the Pigman is lost.
I suggest to change the function of the egg from place block, to break block, as when you are using a spawn egg, you're not going to be attacking what you just spawned.

**Comment by Flemmli97** [comment]
But it is already left click (break block) to save and right click to spawn an entity

**Comment by Flemmli97** [comment]
is this still relevant?

**Comment by Flemmli97** [comment]
closed
