### ISSUE TITLE
Crash when shift clicking item in mob equipment gui

### ISSUE THREAD

**Issue by KaratFeng** [Flemmli97/MobBattle#40]
### Modloader

Forge

### Minecraft version

1.21.1

### Modloader version

Neoforge

### Mod version

mobbattle-1.21.1-2.4.10-neoforge

### Description

I Tried to shift click a trident in a drowned inventory and it crashed

### Steps to reproduce

1. Step one open a drown inventory with the equipement wand
2. step 2: shift clic a trident

### Logs

[crash-2024-07-28_22.38.34-fml.txt](https://github.com/user-attachments/files/16964549/crash-2024-07-28_22.38.34-fml.txt)

**Comment by Flemmli97** [comment]
its saying something about spawnplaceevent which this mod doesnt ever call. are you sure its the right logs? 
the stacktrace indicates it happens during startup of the game

**Comment by KaratFeng** [comment]
weird. it generated a crash log when I did that, i'll reproduce it and add the latest log
[latest.log](https://github.com/user-attachments/files/17002577/latest.log)

**Comment by KaratFeng** [comment]
[crash-2024-09-14_09.20.55-client.txt](https://github.com/user-attachments/files/17002579/crash-2024-09-14_09.20.55-client.txt)
here's another crash report too just in case I messed up
