### ISSUE TITLE
[Feature Request]: 2.4.12 features for 1.19.2 and 1.20.1

### ISSUE THREAD

**Issue by PiggySkillsX** [Flemmli97/MobBattle#42]
### Suggestions

Can you please port features added in 2.4.12 to 1.19.2 and 1.20.1? Those versions are still popular and will be for a while.

**Comment by Flemmli97** [comment]
closed in bcecd9d516e8e3759b28d4c9cf71941144c564e4.
1.19.2 will not be updated though
