### ISSUE TITLE
If installed with the Pet Bats mod, the bats will no longer attack mobs the owner attack.

### ISSUE THREAD

**Issue by abidoang** [Flemmli97/MobBattle#6]
#### Issue (The better the description the better i can solve the issue):
If this mod is installed along with the Pet Bats mod, the pet bats will no longer attack mobs the owner attack.

#### Steps to reproduce:
Install the pet bats mod along with mob battle mod.

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2814
- MobBattle: MobBattleMod-1.12.2-2.3.2.jar

#### Other Mods (If you think it might be cause of an incompability):
- Pet Bats (link: https://www.curseforge.com/minecraft/mc-mods/pet-bats)

**Comment by Flemmli97** [comment]
i guess ur using latest pet bat version? since neither u nor the files on curseforge have version numbers

**Comment by abidoang** [comment]
Yes indeed. The latest version of it was back in January 2018

**Comment by Flemmli97** [comment]
reopen if this is still relevant
