### ISSUE TITLE
Crashes server.

### ISSUE THREAD

**Issue by grandogarndo** [Flemmli97/MobBattle#7]
#### Issue (The better the description the better i can solve the issue):
When i go on my server(with correct forge version installed) the launcher says cannot connect to server. Mcprohosting says i need to pay for modpack support.

#### Affected Versions (Latest is NOT a version):

- Minecraft:1.14.4
- Forge:28.1.44
- MobBattle:2.3.2

**Comment by grandogarndo** [comment]
how do i get logs?

**Comment by Flemmli97** [comment]
its in your mc folder -> /logs. also dont copy paste it here. use pastebin or something

**Comment by grandogarndo** [comment]
its all just gibberish. are you sure that's the right folder? also how do i locate the right log is that is the right folder?

**Comment by Flemmli97** [comment]
there should be a file called latest.log and debug.log. which are the log files for the last time you launched mc

**Comment by grandogarndo** [comment]
ok thanks

**Comment by grandogarndo** [comment]
okay, now the server works, but their is nothing in the mob battle mod tab. before i enter it says "Incompatible FML modded server, Server mod list is not compatible" The server has the same exact mods.

**Comment by Flemmli97** [comment]
still need the logs

**Comment by Flemmli97** [comment]
always always include logs. nothing can be done without logs

**Comment by grandogarndo** [comment]
ok coming up

**Comment by grandogarndo** [comment]
[latest.log](https://github.com/Flemmli97/MobBattle/files/3776355/latest.log)
[debug.log](https://github.com/Flemmli97/MobBattle/files/3776356/debug.log)

**Comment by Flemmli97** [comment]
can you try now the new version and see if it works?

**Comment by grandogarndo** [comment]
I think it is just mcprohosting's thirst for money, they want you to pay money for a custom mod pack if you don't want to use their mods.

**Comment by Flemmli97** [comment]
the version before crashed the server and i fixed it. they might have taken out the mod to run the server cause the log says the mod isnt on the server

**Comment by Flemmli97** [comment]
issue seems resolved
