### ISSUE TITLE
[1.12.2] None of the wands works

### ISSUE THREAD

**Issue by Dimentive** [Flemmli97/MobBattle#8]
#### Issue

The mob killer wand does not kill mobs when left-clicking, the mob healer wand does not heal mobs, the mob enrager wand does not enrage mods, and so on. Not a single one of the items that this mod adds works for me.

#### Steps to reproduce

Use the wands.

#### Affected versions

* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2847
* **Mob Battle Mod:** 2.3.3

#### Other mods

[Full mod list.](https://pastebin.com/raw/GqtNf8XD)

I have a _lot_ of mods installed, and since this bug is so major (the entire mod just doesn’t work), I’m assuming you would’ve caught it, which tells me that this is a conflict between Mob Battle Mod and one of the other mods that I’m using.

**Comment by Flemmli97** [comment]
this is a big modlist. can you do it like this: remove half of the mod. try again and if its still not working then keep doing this, else test with the other half. that way its faster to single out the conflicting mod

**Comment by Flemmli97** [comment]
closed due to inactivity
